name: Deploy Kong API Gateway
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure AKS context
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: testcluster
          resource-group: testspring
      - uses: Azure/k8s-deploy@v1
        with:
          namespace: kong
          manifests: |
            manifests/deployment.yml